### Example Fixed Project

The rest of this tutorial uses pre compiled ORBIT configs that are stored as .yaml files in the '~/configs/ folder. There are load and save methods available in ORBIT for working with .yaml files. These example projects each exhibit different functionalities within ORBIT. Using these examples and combinations of them, most project configurations can be modeled.

In [2]:
import os
import pandas as pd
from ORBIT import ProjectManager, load_config

weather = pd.read_csv("data/example_weather.csv", parse_dates=["datetime"])\
            .set_index("datetime")

### Load the project configuration

In [10]:
fixed_config = load_config("configs/example_fixed_project.yaml")  # Configs can be loaded with absolute or relative paths

print(type(fixed_config))                                         # They are loaded in as dictionaries.

print(f"Num turbines: {fixed_config['plant']['num_turbines']}")   # Once a configuration is loaded, different parameters can  
print(f"Turbine: {fixed_config['turbine']}")                      # be accessed using dict access.
print(f"\nSite: {fixed_config['site']}")

<class 'dict'>
Num turbines: 50
Turbine: SWT_6MW_154m_110m

Site: {'depth': 22.5, 'distance': 124, 'distance_to_landfall': 35, 'mean_windspeed': 9}

### Phases

This fixed project represents a generic Offshore Wind farm with 50 6MW turbines. It includes 5 design modules and 6 installation modules as seen below. This is a common set of modules to run for a fixed bottom project. This config will model the procurement and installation of monopiles, scour protection, array system, export system, offshore substation and the turbines.

In [11]:
print(f"Design phases: {fixed_config['design_phases']}")
print(f"\nInstall phases: {list(fixed_config['install_phases'].keys())}")

Design phases: ['MonopileDesign', 'ScourProtectionDesign', 'ArraySystemDesign', 'ExportSystemDesign', 'OffshoreSubstationDesign']

Install phases: ['ArrayCableInstallation', 'ExportCableInstallation', 'MonopileInstallation', 'OffshoreSubstationInstallation', 'ScourProtectionInstallation', 'TurbineInstallation']

### Run

This project is always being modeled with the example weather project supplied that is representative of US East Coast wind farm locations.

In [12]:
project = ProjectManager(fixed_config, weather=weather)
project.run()

ORBIT library intialized at '/Users/jnunemak/Fun/repos/ORBIT/library'

### Top Level Outputs

ProjectManager offers several high level result categories:
- Installation CapEx
- System CapEx (procurement of BOS subcomponents)
- Turbine CapEx
- Soft CapEx (project management costs)
- Total CapEx
- Total installation time
- etc.

In [13]:
print(f"Installation CapEx:  {project.installation_capex/1e6:.0f} M")
print(f"System CapEx:        {project.system_capex/1e6:.0f} M")
print(f"Turbine CapEx:       {project.turbine_capex/1e6:.0f} M")
print(f"Soft CapEx:          {project.soft_capex/1e6:.0f} M")
print(f"Total CapEx:        {project.total_capex/1e6:.0f} M")

print(f"\nInstallation Time: {project.installation_time:.0f} h")

Installation CapEx:  181 M
System CapEx:        257 M
Turbine CapEx:       390 M
Soft CapEx:          194 M
Total CapEx:        1173 M

Installation Time: 12731 h

### CapEx Breakdown

In [14]:
# The breakdown of project costs by module is available  at 'capex_breakdown'
project.capex_breakdown

{'Array System': 24416575.834140003,
 'Export System': 22813500.0,
 'Offshore Substation': 49739550.0,
 'Scour Protection': 5896000,
 'Substructure': 154436243.91851607,
 'Array System Installation': 19828893.780554257,
 'Export System Installation': 63231897.48006167,
 'Offshore Substation Installation': 4323839.723173516,
 'Scour Protection Installation': 19613097.60273973,
 'Substructure Installation': 28858058.87808971,
 'Turbine Installation': 44667905.25114152,
 'Turbine': 390000000,
 'Soft': 193500000,
 'Project': 151250000.0}

### Installation Actions

In [17]:
df = pd.DataFrame(project.actions)    # The project simulation logs are also available for all modules
df

,cost_multiplier,agent,action,duration,cost,level,time,phase,phase_name,max_waveheight,max_windspeed,transit_speed,location,site_depth,hub_height
0,0.5,Array Cable Installation Vessel,Mobilize,72.000000,180000.0,ACTION,0.000000,ArrayCableInstallation,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.5,Heavy Lift Vessel,Mobilize,72.000000,750000.0,ACTION,0.000000,OffshoreSubstationInstallation,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.5,Feeder 0,Mobilize,72.000000,180000.0,ACTION,0.000000,OffshoreSubstationInstallation,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.5,SPI Vessel,Mobilize,72.000000,180000.0,ACTION,0.000000,ScourProtectionInstallation,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,SPI Vessel,Load SP Material,4.000000,20000.0,ACTION,4.000000,ScourProtectionInstallation,ScourProtectionInstallation,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3098,NaN,WTIV,Attach Blade,3.500000,26250.0,ACTION,5758.182005,TurbineInstallation,TurbineInstallation,NaN,NaN,NaN,NaN,22.5,110.0
3099,NaN,WTIV,Release Blade,1.000000,7500.0,ACTION,5759.182005,TurbineInstallation,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3100,NaN,WTIV,Lift Blade,1.100000,8250.0,ACTION,5760.282005,TurbineInstallation,TurbineInstallation,NaN,NaN,NaN,NaN,22.5,110.0
3101,NaN,WTIV,Attach Blade,3.500000,26250.0,ACTION,5763.782005,TurbineInstallation,TurbineInstallation,NaN,NaN,NaN,NaN,22.5,110.0
3102,NaN,WTIV,Jackdown,0.316667,2375.0,ACTION,5764.098671,TurbineInstallation,TurbineInstallation,NaN,NaN,NaN,NaN,22.5,110.0

In [19]:
# These logs can be sorted by phase by using DataFrame operations

turbine_install = df.loc[df['phase']=="TurbineInstallation"]
turbine_install

,cost_multiplier,agent,action,duration,cost,level,time,phase,phase_name,max_waveheight,max_windspeed,transit_speed,location,site_depth,hub_height
517,1.0,WTIV,Mobilize,168.000000,1260000.0,ACTION,1524.932005,TurbineInstallation,NaN,NaN,NaN,NaN,NaN,NaN,NaN
523,NaN,WTIV,Fasten Tower Section,4.000000,30000.0,ACTION,1528.932005,TurbineInstallation,TurbineInstallation,NaN,NaN,NaN,NaN,22.5,110.0
527,NaN,WTIV,Fasten Tower Section,4.000000,30000.0,ACTION,1532.932005,TurbineInstallation,TurbineInstallation,NaN,NaN,NaN,NaN,22.5,110.0
534,NaN,WTIV,Fasten Nacelle,4.000000,30000.0,ACTION,1536.932005,TurbineInstallation,TurbineInstallation,NaN,NaN,NaN,NaN,22.5,110.0
536,NaN,WTIV,Fasten Blade,1.500000,11250.0,ACTION,1538.432005,TurbineInstallation,TurbineInstallation,NaN,NaN,NaN,NaN,22.5,110.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3098,NaN,WTIV,Attach Blade,3.500000,26250.0,ACTION,5758.182005,TurbineInstallation,TurbineInstallation,NaN,NaN,NaN,NaN,22.5,110.0
3099,NaN,WTIV,Release Blade,1.000000,7500.0,ACTION,5759.182005,TurbineInstallation,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3100,NaN,WTIV,Lift Blade,1.100000,8250.0,ACTION,5760.282005,TurbineInstallation,TurbineInstallation,NaN,NaN,NaN,NaN,22.5,110.0
3101,NaN,WTIV,Attach Blade,3.500000,26250.0,ACTION,5763.782005,TurbineInstallation,TurbineInstallation,NaN,NaN,NaN,NaN,22.5,110.0
3102,NaN,WTIV,Jackdown,0.316667,2375.0,ACTION,5764.098671,TurbineInstallation,TurbineInstallation,NaN,NaN,NaN,NaN,22.5,110.0

In [20]:
# Operations can also be grouped to see a total amount of time spend on each operation

turbine_install.groupby(["action"]).sum()['duration']

action
Attach Blade             525.000000
Attach Nacelle           300.000000
Attach Tower Section     600.000000
Delay                    669.000000
Fasten Blade             225.000000
Fasten Nacelle           200.000000
Fasten Tower Section     400.000000
Jackdown                  15.833333
Jackup                    15.833333
Lift Blade               165.000000
Lift Nacelle              55.000000
Lift Tower Section        82.500000
Mobilize                 168.000000
Position Onsite          100.000000
Reequip                  100.000000
Release Blade            150.000000
Release Nacelle          150.000000
Release Tower Section    300.000000
Transit                  186.000000
Name: duration, dtype: float64